services:
  db:
    image: postgres:16
    container_name: doc_analyzer_ai_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "doc_analyzer_ai_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "123"
    volumes:
      - ./db_data_local:/var/lib/postgresql/data
      - ./configs/postgresql.conf:/var/lib/postgresql/data/postgresql.conf # <-- Ensure this is also pointed to /data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: doc_analyzer_ai_app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: "db" # 'db' is the service name within the Docker network
      DB_PORT: "5432"
      DB_USER: "user"
      DB_PASSWORD: "123"
      DB_NAME: "doc_analyzer_ai_db"
    depends_on:
      db:
        condition: service_healthy